### ISSUE TITLE
No file menu on startup

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-maya#14]
When having other tools that adds to the File menu, like Red9, the userSetup line `pyblish_maya.lib.add_to_filemenu()` error out and nothing gets added to the File menu.

A solution is to encapsulate the line with an evalDeferred;
```python
cmds.evalDeferred('pyblish_maya.lib.add_to_filemenu()')
```

**Comment by mottosso** [comment]
This was solved a few versions ago
