### ISSUE TITLE
some install error

### ISSUE THREAD

**Issue by zaiyicheng** [pyblish/pyblish-maya#34]
I installed pyblish_maya use pip. but It shows 

```
"C:\Python27\Lib\site-packages\pyblish_endpoint\vendor\jsonschema\schemas" do not have draft3.json. 
```

So I have to downloaded from GitHub manually.
It also get some other bug. The error shows below:

```
# # C:\Python27\Lib\site-packages\pyblish\main.py:4: UserWarning: main.py deprecated; use util.py
warnings.warn("main.py deprecated; use util.py")
# Warning: Menu item pyblishOpeningDivider does not exist, flag -insertAfter ignored. #
```

The problem is The "File"  menu has  pyblishOpeningDivider menuItem, I have tryed it some times and do not know what caused this.

**Comment by mottosso** [comment]
Hi @zaiyicheng thanks for reporting this, working on a fix now and sorry for the trouble!

**Comment by mottosso** [comment]
Hi @zaiyicheng,

Please find updated installation instructions here.
https://github.com/pyblish/pyblish-suite/wiki/Installation

It's for a central install, but works well for local installs too.

If you have any questions and are looking for immediate feedback, feel free to ask in the [chat room](https://gitter.im/pyblish/pyblish).

**Comment by zaiyicheng** [comment]
OK, I will look at these links ,It's very kind of you.
