### ISSUE TITLE
select_object_set: L35 No accounting for non-unique names. ls(l=False) returns shortest unique path.

### ISSUE THREAD

**Issue by ldunham1** [pyblish/pyblish-maya#41]

**Comment by mottosso** [comment]
Hi @ldunham1, thanks a bunch for the bug reports!

We're actually in the midst of updating [the guide](http://pyblish.com/guide/overview) that go with these plug-ins, as they are out of date and are on their way out and into dedicated packages, such as [Magenta](https://github.com/pyblish/pyblish-magenta) and [Napoleon](https://github.com/pyblish/pyblish-napoleon). Expecting a new release of the guide to take place at the end of June this year.

Till then, you are very welcome to ask both basic and advanced questions on the forum. I'd be happy to provide you with some example material for any specific requirements you may have.

- http://forums.pyblish.com/

See you there? :)

**Comment by ldunham1** [comment]
No problem, will see me there :)

**Comment by mottosso** [comment]
Awesome, looking forward to it! :)
