### ISSUE TITLE
Default plugins run first

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-maya#49]
I was wondering whether we shouldn't have the default plugins run before the default order, so https://github.com/pyblish/pyblish-maya/blob/master/pyblish_maya/plugins/select_current_file.py gets an order of ```pyblish.api.Collector.order - 0.5```?

**Comment by mottosso** [comment]
Sounds good to me.

If you have an opportunity to test this out, feel free to either let me know of submit a PR.

**Comment by BigRoy** [comment]
This is implemented with #51
