### ISSUE TITLE
about pyblish port

### ISSUE THREAD

**Issue by heylenz** [pyblish/pyblish-maya#54]
I can't use pyblish-maya, I see the output of the Maya Listening on 127.0.0.1:9036,   in pyblish Terminal, I see port 9002, do not know if this is not the reason I cannot use!

**Comment by heylenz** [comment]
I know how to solve this problem, the system process inside the closure of python.exe then you can kill it,after that port will ok!

**Comment by mottosso** [comment]
Hi @heylenz, glad to hear you got it working! I would be very interested in finding out what caused this problem to begin with. If you are seeing port `9036`, that means that you are having `36` Maya's, or similar software, already open on your computer, which seems a bit odd.

In Maya, you can query the current port used for the GUI with this:

```python
from pyblish_integration.lib import port
print(port)
```

Have a look at the developer docs for more hints.

- https://pyblish.gitbooks.io/developer-guide/content/communicating_with_the_ui.html
