### ISSUE TITLE
_show_no_gui() takes no arguments (1 given) 

### ISSUE THREAD

**Issue by llPekoll** [pyblish/pyblish-maya#72]
`# Error: TypeError: file /users/peko/.local/lib/python2.7/site-packages/pyblish_maya/lib.py line 67: _show_no_gui() takes no arguments (1 given) # 
`
I've seen this Error ib Solved issue(closed), but It's still comes up

when I do 

```
import pyblish_maya
pyblish_maya.show()
```

**Comment by llPekoll** [comment]
pyblish_qml.show() stuck at loading screen
pyblish_lite.show() does display the pyblish window

**Comment by tokejepsen** [comment]
Hey @llPekoll,

I've just pushed an update to fix your issue: https://github.com/pyblish/pyblish-maya/releases/tag/2.1.5

Could you confirm it works?

> pyblish_qml.show() stuck at loading screen

You might need more setup to get pyblish_qml working. That means getting PyQt5 up and running.

**Comment by llPekoll** [comment]
Thanks a lot @tokejepsen 
`pyblish_maya.show()`
Is working now
I'll try to work with that :+1: 

`pyblish_qml.show()`
returns me `# Error: invalid syntax # ` like you implicitly said
