### ISSUE TITLE
import error on pyblish-maya 2.1.7

### ISSUE THREAD

**Issue by Ennosch** [pyblish/pyblish-maya#76]
hey, 

I had this ImportError happening for the publish-maya 2.1.7 release
(from the Maya Script Editor)
```python
import pyblish_maya
# Error: ImportError: file /home/enno.schluender/dev/pyblish_test/pyblish-maya/pyblish_maya/lib.py line 15: cannot import name plugins # 
```

when I replaced publish_maya/vendor/Qt.py 
with the Qt.py 1.2.5 version from here
https://github.com/mottosso/Qt.py/blob/1.2.5/Qt.py
it seems to work fine. 

I am I doing something wrong ?

**Comment by Ennosch** [comment]
Note, I got that error when I used the pip installation of pyblish.
Which made me wonder more about that error in the first place.
```
Package                            Version
---------------------------------- -------
backports.shutil-get-terminal-size 1.0.0
decorator                          4.4.1
enum34                             1.1.6
ipython                            5.9.0
ipython-genutils                   0.2.0
pathlib2                           2.3.5
pexpect                            4.8.0
pickleshare                        0.7.5
pip                                20.1
prompt-toolkit                     1.0.18
ptvsd                              4.3.2
ptyprocess                         0.6.0
pyblish                            1.7.0
pyblish-base                       1.8.7
pyblish-houdini                    1.0.1
pyblish-lite                       0.8.5
pyblish-maya                       2.1.7
pyblish-nuke                       2.1.2
pyblish-qml                        1.11.4
Pygments                           2.5.2
scandir                            1.10.0
setuptools                         44.1.0
simplegeneric                      0.8.1
six                                1.14.0
traitlets                          4.3.3
virtualenv                         16.7.9
wcwidth                            0.1.8
wheel                              0.34.2 
```

**Comment by mottosso** [comment]
Hm, I can't figure out how the error relates to Qt.py. On the next line, it tries importing Qt.py. Could the error be related to not having access to PyQt5/PySide2/PySide2 or PyQt4 on your PYTHONPATH during import?

**Comment by Ennosch** [comment]
Hey, 
thanks for getting back so quickly


I am not using any external  PyQt5/PySide2/PySide2 or PyQt4.
(did I miss something in the docs ?)
```
import PySide2
# Result: <module 'PySide2' from '/usr/autodesk/maya2020/lib/python2.7/site-packages/PySide2/__init__.py'> # 
```
PYTHONPATH is not point to any qt modules I think 
```
os.getenv('PYTHONPATH')
-->
['/home/tmp_usr/dev/pyblish_test/pyblish-base',
 '/home/tmp_usr/dev/pyblish_test/pyblish-maya',
 '/home/tmp_usr/dev/pyblish_test/pyblish-lite',
 '/home/tmp_usr/dev/pyblish_test/pyblish-qml', ...]
```

**Comment by mottosso** [comment]
No you didn't miss anything, there just need to be a Qt binding on your path. Ok, seeing as this is Maya 2020, I remember seeing this problem before.

There's a solution here I think: https://forums.pyblish.com/t/pyblish-and-maya-2020/605

But if upgrading Qt.py solves it as well, then that would be much preferable. Would you be able to submit a PR with your changes?

**Comment by Ennosch** [comment]
hey, 
I have created a pull request here, 
but really just to compare differencest in those Qt.py(s)

I did not have an actual closer look at the code myself though.

**Comment by mottosso** [comment]
Thanks @Ennosch, me and all future users of Maya 2020 thanks you. :) Feel free to close this issue if all is well.
